### ISSUE TITLE
One screenshot is not properly shown in the website

### ISSUE THREAD

**Issue by jgarciao** [flathub/net.baseart.Glide#1]
One of the screenshots is not properly shown in [flathub.org](https://flathub.org/apps/details/net.baseart.Glide). The original image might be fine but when converted to different resolutions by the flathub build process it looks like an [empty gray image](https://flathub.org/repo/screenshots/net.baseart.Glide-stable/752x423/net.baseart-9dc106a064683c9405ca56bce2673122.png)

I've seen a similar problem in the past and the solution was to use a source image that has 16:9. See [this issue](https://github.com/flathub/org.kde.kontact/issues/1) for more info.

**Comment by philn** [comment]
Fixed in 0.5.6 :)
