### ISSUE TITLE
gst-libav and gstreamer-vaapi are available in org.gnome.Platform

### ISSUE THREAD

**Issue by Erick555** [flathub/net.baseart.Glide#6]
[gst-libav](https://github.com/flathub/net.baseart.Glide/blob/master/net.baseart.Glide.yaml#L72) and [gstreamer-vaapi](https://github.com/flathub/net.baseart.Glide/blob/master/net.baseart.Glide.yaml#L82) are available in `org.gnome.Platform`, why are they bundled in app?

**Comment by TingPing** [comment]
They have a very minimal set of codecs and media players generally want everything.

**Comment by philn** [comment]
I'll try to unbundle gst-vaapi then :)

**Comment by philn** [comment]
gst-vaapi doesn't seem to be shipped in the GNOME 3.30 runtime:
```
$ flatpak run --command=/bin/bash  net.baseart.Glide/x86_64/master
$ gst-inspect-1.0 vaapi
No such element or plugin 'vaapi'
```

**Comment by TingPing** [comment]
Perhaps it should be requested.

**Comment by philn** [comment]
Agreed, requested over at https://gitlab.gnome.org/GNOME/gnome-build-meta/issues/118

**Comment by philn** [comment]
gstreamer-vaapi was added in the runtime, then removed, then some idea of an extension appeared, but https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/1750 was never merged...

**Comment by Erick555** [comment]
There is a new attempt to make gst-vaapi extension: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/3760 . If this is ever merged and published on flathub then you may consider using it over bundled one.

**Comment by philn** [comment]
Yeah I noticed it. Will keep an eye on it :)
